package pro.yakuraion.parish.commonui.compose.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF2B59B9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDAE2FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001847)
val md_theme_light_secondary = Color(0xFF585E71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDCE2F9)
val md_theme_light_onSecondaryContainer = Color(0xFF151B2C)
val md_theme_light_tertiary = Color(0xFF9B4053)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD9DD)
val md_theme_light_onTertiaryContainer = Color(0xFF400014)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD5)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFEFBFF)
val md_theme_light_onBackground = Color(0xFF1B1B1F)
val md_theme_light_surface = Color(0xFFFBF8FD)
val md_theme_light_onSurface = Color(0xFF1B1B1F)
val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF44464F)
val md_theme_light_outline = Color(0xFF757780)
val md_theme_light_inverseOnSurface = Color(0xFFF2F0F4)
val md_theme_light_inverseSurface = Color(0xFF303034)
val md_theme_light_inversePrimary = Color(0xFFB1C5FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF2B59B9)
val md_theme_light_outlineVariant = Color(0xFFC5C6D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB1C5FF)
val md_theme_dark_onPrimary = Color(0xFF002C71)
val md_theme_dark_primaryContainer = Color(0xFF00409F)
val md_theme_dark_onPrimaryContainer = Color(0xFFDAE2FF)
val md_theme_dark_secondary = Color(0xFFC0C6DD)
val md_theme_dark_onSecondary = Color(0xFF2A3042)
val md_theme_dark_secondaryContainer = Color(0xFF404659)
val md_theme_dark_onSecondaryContainer = Color(0xFFDCE2F9)
val md_theme_dark_tertiary = Color(0xFFFFB2BD)
val md_theme_dark_onTertiary = Color(0xFF5F1127)
val md_theme_dark_tertiaryContainer = Color(0xFF7D293C)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD9DD)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF930009)
val md_theme_dark_onError = Color(0xFF690004)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD5)
val md_theme_dark_background = Color(0xFF1B1B1F)
val md_theme_dark_onBackground = Color(0xFFE4E2E6)
val md_theme_dark_surface = Color(0xFF131316)
val md_theme_dark_onSurface = Color(0xFFC7C6CA)
val md_theme_dark_surfaceVariant = Color(0xFF44464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC5C6D0)
val md_theme_dark_outline = Color(0xFF8F9099)
val md_theme_dark_inverseOnSurface = Color(0xFF1B1B1F)
val md_theme_dark_inverseSurface = Color(0xFFE4E2E6)
val md_theme_dark_inversePrimary = Color(0xFF2B59B9)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFB1C5FF)
val md_theme_dark_outlineVariant = Color(0xFF44464F)
val md_theme_dark_scrim = Color(0xFF000000)

val extended_theme_light_surface_container_highest = Color(0xFFE4E2E6)
val extended_theme_light_surface_container_high = Color(0xFFE9E7EC)
val extended_theme_light_surface_container = Color(0xFFEFEDF1)
val extended_theme_light_surface_container_low = Color(0xFFF5F3F7)
val extended_theme_light_surface_container_lowest = Color(0xFFFFFFFF)

val extended_theme_dark_surface_container_highest = Color(0xFF343438)
val extended_theme_dark_surface_container_high = Color(0xFF292A2D)
val extended_theme_dark_surface_container = Color(0xFF1F1F23)
val extended_theme_dark_surface_container_low = Color(0xFF1B1B1F)
val extended_theme_dark_surface_container_lowest = Color(0xFF0D0E11)
